export const DummyData = [
  {
    id: '1000',
    email: 'bamboo.watch@example.com',
    name: 'Bamboo Watch',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    phoneNumber: '+1-555-0100',
    date: '16 August 2025'
  },
  {
    id: '1001',
    email: 'black.watch@example.com',
    name: 'Black Watch',
    description: 'Product Description',
    image: 'black-watch.jpg',
    price: 72,
    category: 'Accessories',
    quantity: 61,
    inventoryStatus: 'INSTOCK',
    rating: 4,
    phoneNumber: '+1-555-0101',
    date: '17 May 2025'
  },
  {
    id: '1002',
    email: 'blue.band@example.com',
    name: 'Blue Band',
    description: 'Product Description',
    image: 'blue-band.jpg',
    price: 79,
    category: 'Fitness',
    quantity: 2,
    inventoryStatus: 'LOWSTOCK',
    rating: 3,
    phoneNumber: '+1-555-0102',
    date: '1 June 2025'
  },
  {
    id: '1003',
    email: 'blue.tshirt@example.com',
    name: 'Blue T-Shirt',
    description: 'Product Description',
    image: 'blue-t-shirt.jpg',
    price: 29,
    category: 'Clothing',
    quantity: 25,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    phoneNumber: '+1-555-0103',
    date: '2 July 2025'
  },
  {
    id: '1004',
    email: 'bracelet@example.com',
    name: 'Bracelet',
    description: 'Product Description',
    image: 'bracelet.jpg',
    price: 15,
    category: 'Accessories',
    quantity: 73,
    inventoryStatus: 'INSTOCK',
    rating: 4,
    phoneNumber: '+1-555-0104',
    date: '16 May 2025'
  },
  {
    id: '1005',
    email: 'brown.purse@example.com',
    name: 'Brown Purse',
    description: 'Product Description',
    image: 'brown-purse.jpg',
    price: 120,
    category: 'Accessories',
    quantity: 0,
    inventoryStatus: 'OUTOFSTOCK',
    rating: 4,
    phoneNumber: '+1-555-0105',
    date: '16 May 2025'
  }
];